### PR TITLE
#3 Ported 279 from ZF repository - fixes merging of duplicate delegator factory definitions

### LINKED ISSUE #3: Hotfix #279
Fix issue #279 

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-servicemanager/pull/280

### PR DESCRIPTION
**Pull request by GeeH**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description
Bug fix from old repostiory at https://github.com/zendframework/zend-servicemanager/pull/280

Thanks @thomasvargiu 

Fixes #3

### CODE REVIEW

**Comment by GeeH** [comment]
Closes #3

File: src/ServiceManager.php [hunk 1]
```diff
@@ -737,6 +737,32 @@ private function createLazyServiceDelegatorFactory()
...
+     * It works with strings and class instances.
+     * It's not possible to de-duple anonymous functions
+     *
+     * @param string[][]|Factory\DelegatorFactoryInterface[][] $config
+     * @return string[][]|Factory\DelegatorFactoryInterface[][]
+     */
+    private function mergeDelegators(array $config)
+    {
+        foreach ($config as $key => $delegators) {
+            if (! isset($this->delegators[$key])) {
```
Comment (Ocramius) [inline src/ServiceManager.php:751]: This should probably be an `array_key_exists()` check to prevent `isset()` semantics (`isset()` can work with undefined variables, which may happen when refactoring at a later point in time)

File: src/ServiceManager.php [hunk 2]
```diff
@@ -737,6 +737,32 @@ private function createLazyServiceDelegatorFactory()
...
+                $this->delegators[$key] = $delegators;
+                continue;
+            }
+
+            foreach ($delegators as $delegator) {
+                if (! in_array($delegator, $this->delegators[$key], true)) {
```
Comment (Ocramius) [inline src/ServiceManager.php:757]: This `in_array()` is repeated multiple times: potentially an issue as the array grows.

I don't think it's an issue, since collisions are rare, but worth noting.

Up to you if it needs to be adjusted or not.

File: test/ServiceManagerTest.php [hunk 3]
```diff
@@ -364,4 +365,51 @@ public function testResolvedAliasNoMatchingAbstractFactoryReturnsFalse()
 
         self::assertFalse($serviceManager->has('Alias'));
     }
+
+    /**
+     * Hotfix #3
```
Comment (Ocramius) [inline test/ServiceManagerTest.php:370]: Maybe `@group #3` would be better - not really a hotfix anymore :)

File: test/ServiceManagerTest.php [hunk 4]
```diff
@@ -364,4 +365,51 @@ public function testResolvedAliasNoMatchingAbstractFactoryReturnsFalse()
...
+     * @see https://github.com/laminas/laminas-servicemanager/issues/3
+     */
+    public function testConfigureMultipleTimesAvoidsDuplicates()
+    {
+        $delegatorFactory = function (
+            ContainerInterface $container,
+            $name,
```
Comment (Ocramius) [inline test/ServiceManagerTest.php:377]: Should probably have `string` here

File: test/ServiceManagerTest.php [hunk 5]
```diff
@@ -364,4 +365,51 @@ public function testResolvedAliasNoMatchingAbstractFactoryReturnsFalse()
 
         self::assertFalse($serviceManager->has('Alias'));
     }
+
+    /**
+     * Hotfix #3
+     * @see https://github.com/laminas/laminas-servicemanager/issues/3
+     */
+    public function testConfigureMultipleTimesAvoidsDuplicates()
```
Comment (Ocramius) [inline test/ServiceManagerTest.php:373]: Probably better naming needed: `testConfiguringADelegatorMultipleTimesDoesNotLeadToDuplicateDelegatorCalls()`

File: test/ServiceManagerTest.php [hunk 6]
```diff
@@ -364,4 +365,51 @@ public function testResolvedAliasNoMatchingAbstractFactoryReturnsFalse()
...
+                    return new InvokableObject();
+                },
+            ],
+            'delegators' => [
+                'Foo' => [
+                    $delegatorFactory,
+                    LazyServiceFactory::class,
+                ],
+            ],
+            'lazy_services' => [
```
Comment (Ocramius) [inline test/ServiceManagerTest.php:399]: This test is verifying both the `lazy_services` and the `delegator` changes: should probably be split up into two tests

File: test/ServiceManagerTest.php [hunk 7]
```diff
@@ -364,4 +365,51 @@ public function testResolvedAliasNoMatchingAbstractFactoryReturnsFalse()
...
+            ],
+        ];
+
+        $serviceManager = new ServiceManager($config);
+        $serviceManager->configure($config);
+
+        /** @var InvokableObject $instance */
+        $instance = $serviceManager->get('Foo');
+
+        self::assertInstanceOf(InvokableObject::class, $instance);
```
Comment (Ocramius) [inline test/ServiceManagerTest.php:412]: This assertion is not needed (based on `/** @var */` right above)

File: test/ServiceManagerTest.php (hunk 4 above)
Comment (GeeH) [reply test/ServiceManagerTest.php:377]: I've copied this code from the original repo and cast my eye over it for sanity but I absoltely could add type declarations if we think that's appropriate. My thought was to keep it in line with the existing code which doesn't have type declarations but it's a good chance to start moving in that direction if we think it's a good time to start.

How would we feel about some methods having types and others not?

File: test/ServiceManagerTest.php (hunk 7 above)
Comment (GeeH) [reply test/ServiceManagerTest.php:412]: The `@var` is only an IDE hint and not actually checking that the instance returned is the correct class tho, right?

File: test/ServiceManagerTest.php (hunk 6 above)
Comment (GeeH) [reply test/ServiceManagerTest.php:399]: I think this is OK; it's in the scope of the bugfix imo.

File: test/ServiceManagerTest.php (hunk 4 above)
Comment (weierophinney) [reply test/ServiceManagerTest.php:377]: If we're bumping the PHP version to v3, I'd argue _add them everywhere_ in the test suite.

Comment (Ocramius) [reply test/ServiceManagerTest.php:377]: Yeh, but then not in this patch.

We can run psalter manually in a different patch.

Discussed this with @GeeH and it should be fine as-is for now

File: test/ServiceManagerTest.php (hunk 7 above)
Comment (Ocramius) [reply test/ServiceManagerTest.php:412]: It will likely be picked up by static analysis later, but we can ignore it for now :+1:

**Comment by GeeH** [comment]
Ready for re-review/merge thanks both.

File: src/ServiceManager.php [hunk 8]
```diff
@@ -21,9 +21,9 @@
 use ProxyManager\GeneratorStrategy\EvaluatingGeneratorStrategy;
 use ProxyManager\GeneratorStrategy\FileWriterGeneratorStrategy;
 use Psr\Container\ContainerInterface;
+use Zend\Stdlib\ArrayUtils;
```
Comment (samsonasik) [inline src/ServiceManager.php:24]: /s/Zend/Laminas

**Comment by GeeH** [comment]
ping @Ocramius ?
