### PR TITLE
Narrow array type for `services` in ServiceManager configuration

### LINKED ISSUE #212: Array shape of ServiceManager config contains unspecific array
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.22.0

#### Summary

Not really a bug but more of a QA issue.

The `ServiceManager`s `ServiceManagerConfiguration` array shape contains a `services` key with an unspecific `array` notation. That trips some static analyzers.

#### Current behavior

`ServiceManagerConfiguration` contains the definition: `services?: array<string,object|array>,` which includes a generic `array`.

#### How to reproduce

Use the `ServiceManagerConfiguration` configuration anywhere and run PHPStan (I tried 1.10) which emits `PHPDoc tag @var for variable $serviceManagerConfig has no value type specified in iterable type array.`

#### Expected behavior

PHPStan should not throw an error. This is achieved by using a more "specific" array definition: `array<array-key, mixed>`.

### PR DESCRIPTION
**Pull request by rieschl**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

This PR adds a more specific array shape for the `services` key in `ServiceManagerConfiguration`.

fixes #212

### CODE REVIEW

File: src/ServiceManager.php [hunk 1]
```diff
@@ -89,7 +89,7 @@
  *     initializers?: InitializersConfiguration,
  *     invokables?: array<string,string>,
  *     lazy_services?: LazyServicesConfiguration,
- *     services?: array<string,object|array>,
+ *     services?: array<string,object|array<array-key,mixed>>,
```
Comment (boesing) [inline src/ServiceManager.php]: As requested in #212, please use `array<mixed>` instead.

**Review by boesing — CHANGES_REQUESTED** [review]

File: src/ServiceManager.php (hunk 1 above)
Comment (boesing) [reply src/ServiceManager.php]: @laminas/technical-steering-committee should we enforce this kind of `array` notation via our codestandard and if so, are there existing rules for that? That would prevent us from having these kind of "issues" with incompatibilities between psalm/phpstan in the future.

**Review by boesing — APPROVED** [review]
LGTM, ~will see when I find some time to prepare a release~

nvm, is just a patch. going to release now.

**Comment by rieschl** [comment]
> LGTM, ~will see when I find some time to prepare a release~
> 
> nvm, is just a patch. going to release now.

thanks!
